# Generated by Django 2.2.3 on 2019-07-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elderlyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=30)),
                ('description', models.CharField(blank=True, default='无', max_length=30, null=True)),
                ('date', models.DateField(blank=True)),
            ],
        ),
    ]
