# Generated by Django 2.2.3 on 2019-07-05 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='elderlyInfo',
            new_name='Eventinfo',
        ),
    ]
