# Generated by Django 2.2.2 on 2019-07-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='elderlyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='null', upload_to='user_photo/')),
                ('name', models.CharField(default='null', max_length=30)),
                ('sex', models.CharField(default='null', max_length=4)),
                ('phone_number', models.CharField(default='null', max_length=30)),
                ('id_card', models.CharField(default='null', max_length=30)),
                ('age', models.CharField(default='null', max_length=3)),
                ('admission_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(default='null', max_length=30)),
                ('phone_number', models.CharField(default='null', max_length=30)),
                ('sex', models.CharField(default='null', max_length=4)),
                ('age', models.CharField(default='null', max_length=3)),
                ('address', models.CharField(default='null', max_length=30)),
                ('email', models.CharField(default='null', max_length=30)),
                ('photo', models.ImageField(default='null', upload_to='user_photo/')),
                ('user_email', models.CharField(default='null', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='staffInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='null', upload_to='user_photo/')),
                ('name', models.CharField(default='null', max_length=30)),
                ('sex', models.CharField(default='null', max_length=4)),
                ('phone_number', models.CharField(default='null', max_length=30)),
                ('id_card', models.CharField(default='null', max_length=30)),
                ('age', models.CharField(default='null', max_length=3)),
                ('admission_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='volunteerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='null', upload_to='user_photo/')),
                ('name', models.CharField(default='null', max_length=30)),
                ('sex', models.CharField(default='null', max_length=4)),
                ('phone_number', models.CharField(default='null', max_length=30)),
                ('id_card', models.CharField(default='null', max_length=30)),
                ('age', models.CharField(default='null', max_length=3)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('depart_date', models.DateField(blank=True)),
            ],
        ),
    ]
